WITH payment_history AS (

    SELECT
        ID_CLIENTE                AS CLIENT_ID,
        ID_DOCUMENTO              AS DOCUMENT_ID,
        SAFRA_REF                 AS REFERENCE_CROP,
        DATA_EMISSAO_DOCUMENTO    AS DOCUMENT_ISSUE_DATE,
        DATA_VENCIMENTO           AS DUE_DATE,
        DATA_PAGAMENTO            AS PAYMENT_DATE,
        -- Days of delay (positive = delay, negative = early)
        DATEDIFF(PAYMENT_DATE, DUE_DATE) AS DELAY_DAYS,
        VALOR_A_PAGAR             AS AMOUNT_TO_PAY,
        -- Payment status flags
        CASE WHEN DATEDIFF(PAYMENT_DATE, DUE_DATE) > 0 THEN 1 ELSE 0 END AS LATE_FLAG,
        CASE WHEN DATEDIFF(PAYMENT_DATE, DUE_DATE) >= 5 THEN 1 ELSE 0 END AS DEFAULT_FLAG,
        CASE WHEN DATEDIFF(PAYMENT_DATE, DUE_DATE) < 0 THEN 1 ELSE 0 END AS EARLY_FLAG,
        CASE WHEN DATEDIFF(PAYMENT_DATE, DUE_DATE) = 0 THEN 1 ELSE 0 END AS ON_DUE_DATE_FLAG,
        CASE WHEN DATEDIFF(PAYMENT_DATE, DUE_DATE) <= 0 THEN 1 ELSE 0 END AS ON_TIME_FLAG,
        CASE WHEN DATEDIFF(PAYMENT_DATE, DUE_DATE) <= 4 THEN 1 ELSE 0 END AS NON_DEFAULT_FLAG,
        CASE WHEN DATEDIFF(PAYMENT_DATE, DUE_DATE) < 0
             THEN ABS(DATEDIFF(PAYMENT_DATE, DUE_DATE)) END AS EARLY_DAYS,
        -- Term between issuance and due/payment
        DATEDIFF(DUE_DATE, DOCUMENT_ISSUE_DATE) AS ISSUE_TO_DUE_TERM,
        DATEDIFF(PAYMENT_DATE, DOCUMENT_ISSUE_DATE) AS ISSUE_TO_PAYMENT_DAYS,
        CASE WHEN DATEDIFF(DUE_DATE, DOCUMENT_ISSUE_DATE) > 0
             THEN VALOR_A_PAGAR / DATEDIFF(DUE_DATE, DOCUMENT_ISSUE_DATE) END AS DAILY_CHARGE_AMOUNT
    FROM credit_score.data.pagamentos
        WHERE SAFRA_REF < '{dt_ref}'

),

payment_history_windows AS (

    SELECT
        *,
        -- Temporal window flags
        REFERENCE_CROP > date_add(MONTH, -3, '{dt_ref}')  AS IN_3M,
        REFERENCE_CROP > date_add(MONTH, -6, '{dt_ref}')  AS IN_6M,
        REFERENCE_CROP > date_add(YEAR, -1, '{dt_ref}')   AS IN_12M
    FROM payment_history

),

-- Snapshot of next open bill on reference date
next_due_payment AS (

    SELECT
        ID_CLIENTE AS CLIENT_ID,
        MIN(SAFRA_REF) AS NEXT_DUE_DATE
    FROM credit_score.data.pagamentos
        WHERE DATA_PAGAMENTO IS NULL
          AND SAFRA_REF >= '{dt_ref}'
    GROUP BY ID_CLIENTE

),

payment_history_features AS (

    SELECT

        CLIENT_ID,

        -- ===== Delay count (count of delayed payments) =====
        COALESCE(SUM(CASE WHEN IN_3M THEN LATE_FLAG END), 0)  AS DELAY_COUNT_SUM_3M,
        AVG(CASE WHEN IN_3M THEN LATE_FLAG END)               AS DELAY_COUNT_AVG_3M,
        MIN(CASE WHEN IN_3M THEN LATE_FLAG END)               AS DELAY_COUNT_MIN_3M,
        MAX(CASE WHEN IN_3M THEN LATE_FLAG END)               AS DELAY_COUNT_MAX_3M,

        COALESCE(SUM(CASE WHEN IN_6M THEN LATE_FLAG END), 0)  AS DELAY_COUNT_SUM_6M,
        AVG(CASE WHEN IN_6M THEN LATE_FLAG END)               AS DELAY_COUNT_AVG_6M,
        MIN(CASE WHEN IN_6M THEN LATE_FLAG END)               AS DELAY_COUNT_MIN_6M,
        MAX(CASE WHEN IN_6M THEN LATE_FLAG END)               AS DELAY_COUNT_MAX_6M,

        COALESCE(SUM(CASE WHEN IN_12M THEN LATE_FLAG END), 0) AS DELAY_COUNT_SUM_12M,
        AVG(CASE WHEN IN_12M THEN LATE_FLAG END)              AS DELAY_COUNT_AVG_12M,
        MIN(CASE WHEN IN_12M THEN LATE_FLAG END)              AS DELAY_COUNT_MIN_12M,
        MAX(CASE WHEN IN_12M THEN LATE_FLAG END)              AS DELAY_COUNT_MAX_12M,

        COALESCE(SUM(LATE_FLAG), 0)                           AS DELAY_COUNT_SUM_LIFETIME,
        AVG(LATE_FLAG)                                        AS DELAY_COUNT_AVG_LIFETIME,
        MIN(LATE_FLAG)                                        AS DELAY_COUNT_MIN_LIFETIME,
        MAX(LATE_FLAG)                                        AS DELAY_COUNT_MAX_LIFETIME,

        -- ===== Delay in days =====
        COALESCE(SUM(CASE WHEN IN_3M THEN DELAY_DAYS END), 0) AS DELAY_DAYS_SUM_3M,
        AVG(CASE WHEN IN_3M THEN DELAY_DAYS END)              AS DELAY_DAYS_AVG_3M,
        MIN(CASE WHEN IN_3M THEN DELAY_DAYS END)              AS DELAY_DAYS_MIN_3M,
        MAX(CASE WHEN IN_3M THEN DELAY_DAYS END)              AS DELAY_DAYS_MAX_3M,

        COALESCE(SUM(CASE WHEN IN_6M THEN DELAY_DAYS END), 0) AS DELAY_DAYS_SUM_6M,
        AVG(CASE WHEN IN_6M THEN DELAY_DAYS END)              AS DELAY_DAYS_AVG_6M,
        MIN(CASE WHEN IN_6M THEN DELAY_DAYS END)              AS DELAY_DAYS_MIN_6M,
        MAX(CASE WHEN IN_6M THEN DELAY_DAYS END)              AS DELAY_DAYS_MAX_6M,

        COALESCE(SUM(CASE WHEN IN_12M THEN DELAY_DAYS END), 0) AS DELAY_DAYS_SUM_12M,
        AVG(CASE WHEN IN_12M THEN DELAY_DAYS END)              AS DELAY_DAYS_AVG_12M,
        MIN(CASE WHEN IN_12M THEN DELAY_DAYS END)              AS DELAY_DAYS_MIN_12M,
        MAX(CASE WHEN IN_12M THEN DELAY_DAYS END)              AS DELAY_DAYS_MAX_12M,

        COALESCE(SUM(DELAY_DAYS), 0)                           AS DELAY_DAYS_SUM_LIFETIME,
        AVG(DELAY_DAYS)                                        AS DELAY_DAYS_AVG_LIFETIME,
        MIN(DELAY_DAYS)                                        AS DELAY_DAYS_MIN_LIFETIME,
        MAX(DELAY_DAYS)                                        AS DELAY_DAYS_MAX_LIFETIME,

        -- ===== Total amount paid =====
        COALESCE(SUM(CASE WHEN IN_3M THEN AMOUNT_TO_PAY END), 0) AS AMOUNT_PAID_SUM_3M,
        AVG(CASE WHEN IN_3M THEN AMOUNT_TO_PAY END)              AS AMOUNT_PAID_AVG_3M,
        MIN(CASE WHEN IN_3M THEN AMOUNT_TO_PAY END)              AS AMOUNT_PAID_MIN_3M,
        MAX(CASE WHEN IN_3M THEN AMOUNT_TO_PAY END)              AS AMOUNT_PAID_MAX_3M,

        COALESCE(SUM(CASE WHEN IN_6M THEN AMOUNT_TO_PAY END), 0) AS AMOUNT_PAID_SUM_6M,
        AVG(CASE WHEN IN_6M THEN AMOUNT_TO_PAY END)              AS AMOUNT_PAID_AVG_6M,
        MIN(CASE WHEN IN_6M THEN AMOUNT_TO_PAY END)              AS AMOUNT_PAID_MIN_6M,
        MAX(CASE WHEN IN_6M THEN AMOUNT_TO_PAY END)              AS AMOUNT_PAID_MAX_6M,

        COALESCE(SUM(CASE WHEN IN_12M THEN AMOUNT_TO_PAY END), 0) AS AMOUNT_PAID_SUM_12M,
        AVG(CASE WHEN IN_12M THEN AMOUNT_TO_PAY END)              AS AMOUNT_PAID_AVG_12M,
        MIN(CASE WHEN IN_12M THEN AMOUNT_TO_PAY END)              AS AMOUNT_PAID_MIN_12M,
        MAX(CASE WHEN IN_12M THEN AMOUNT_TO_PAY END)              AS AMOUNT_PAID_MAX_12M,

        COALESCE(SUM(AMOUNT_TO_PAY), 0) AS AMOUNT_PAID_SUM_LIFETIME,
        AVG(AMOUNT_TO_PAY)              AS AMOUNT_PAID_AVG_LIFETIME,
        MIN(AMOUNT_TO_PAY)              AS AMOUNT_PAID_MIN_LIFETIME,
        MAX(AMOUNT_TO_PAY)              AS AMOUNT_PAID_MAX_LIFETIME,

        -- ===== Recency: days since last relevant event =====
        DATEDIFF('{dt_ref}', MAX(CASE WHEN LATE_FLAG = 1 THEN DUE_DATE END))        AS DAYS_SINCE_LAST_DELAY,
        DATEDIFF('{dt_ref}', MAX(CASE WHEN DEFAULT_FLAG = 1 THEN DUE_DATE END))     AS DAYS_SINCE_LAST_DEFAULT,
        DATEDIFF('{dt_ref}', MAX(PAYMENT_DATE))                                     AS DAYS_SINCE_LAST_PAYMENT,

        -- ===== Early payments count =====
        COALESCE(SUM(CASE WHEN IN_3M THEN EARLY_FLAG END), 0)  AS EARLY_COUNT_3M,
        COALESCE(SUM(CASE WHEN IN_6M THEN EARLY_FLAG END), 0)  AS EARLY_COUNT_6M,
        COALESCE(SUM(CASE WHEN IN_12M THEN EARLY_FLAG END), 0) AS EARLY_COUNT_12M,
        COALESCE(SUM(EARLY_FLAG), 0)                           AS EARLY_COUNT_LIFETIME,

        -- ===== Average and sum of early days =====
        COALESCE(SUM(CASE WHEN IN_3M THEN EARLY_DAYS END), 0)  AS EARLY_DAYS_SUM_3M,
        AVG(CASE WHEN IN_3M THEN EARLY_DAYS END)               AS EARLY_DAYS_AVG_3M,

        COALESCE(SUM(CASE WHEN IN_6M THEN EARLY_DAYS END), 0)  AS EARLY_DAYS_SUM_6M,
        AVG(CASE WHEN IN_6M THEN EARLY_DAYS END)               AS EARLY_DAYS_AVG_6M,

        COALESCE(SUM(CASE WHEN IN_12M THEN EARLY_DAYS END), 0) AS EARLY_DAYS_SUM_12M,
        AVG(CASE WHEN IN_12M THEN EARLY_DAYS END)              AS EARLY_DAYS_AVG_12M,

        COALESCE(SUM(EARLY_DAYS), 0)                           AS EARLY_DAYS_SUM_LIFETIME,
        AVG(EARLY_DAYS)                                        AS EARLY_DAYS_AVG_LIFETIME,

        -- ===== On-time payments count =====
        COALESCE(SUM(CASE WHEN IN_3M THEN ON_DUE_DATE_FLAG END), 0)  AS ON_DUE_DATE_COUNT_3M,
        COALESCE(SUM(CASE WHEN IN_6M THEN ON_DUE_DATE_FLAG END), 0)  AS ON_DUE_DATE_COUNT_6M,
        COALESCE(SUM(CASE WHEN IN_12M THEN ON_DUE_DATE_FLAG END), 0) AS ON_DUE_DATE_COUNT_12M,
        COALESCE(SUM(ON_DUE_DATE_FLAG), 0)                           AS ON_DUE_DATE_COUNT_LIFETIME,

        -- ===== Invoices issued count =====
        COALESCE(COUNT(CASE WHEN IN_3M THEN 1 END), 0)  AS INVOICES_ISSUED_3M,
        COALESCE(COUNT(CASE WHEN IN_6M THEN 1 END), 0)  AS INVOICES_ISSUED_6M,
        COALESCE(COUNT(CASE WHEN IN_12M THEN 1 END), 0) AS INVOICES_ISSUED_12M,
        COALESCE(COUNT(*), 0)                           AS INVOICES_ISSUED_LIFETIME,

        -- ===== Requested amount =====
        AVG(CASE WHEN IN_3M THEN AMOUNT_TO_PAY END)  AS REQUESTED_AMOUNT_AVG_3M,
        MAX(CASE WHEN IN_3M THEN AMOUNT_TO_PAY END)  AS REQUESTED_AMOUNT_MAX_3M,

        AVG(CASE WHEN IN_6M THEN AMOUNT_TO_PAY END)  AS REQUESTED_AMOUNT_AVG_6M,
        MAX(CASE WHEN IN_6M THEN AMOUNT_TO_PAY END)  AS REQUESTED_AMOUNT_MAX_6M,

        AVG(CASE WHEN IN_12M THEN AMOUNT_TO_PAY END) AS REQUESTED_AMOUNT_AVG_12M,
        MAX(CASE WHEN IN_12M THEN AMOUNT_TO_PAY END) AS REQUESTED_AMOUNT_MAX_12M,

        AVG(AMOUNT_TO_PAY) AS REQUESTED_AMOUNT_AVG_LIFETIME,
        MAX(AMOUNT_TO_PAY) AS REQUESTED_AMOUNT_MAX_LIFETIME,

        -- ===== On-time payment percentage (não atrasados) =====
        AVG(CASE WHEN IN_3M THEN ON_TIME_FLAG END)  AS ON_TIME_PCT_3M,
        AVG(CASE WHEN IN_6M THEN ON_TIME_FLAG END)  AS ON_TIME_PCT_6M,
        AVG(CASE WHEN IN_12M THEN ON_TIME_FLAG END) AS ON_TIME_PCT_12M,
        AVG(ON_TIME_FLAG)                           AS ON_TIME_PCT_LIFETIME,

        -- ===== Non-default payment percentage (atraso <= 4 dias) =====
        AVG(CASE WHEN IN_3M THEN NON_DEFAULT_FLAG END)  AS NON_DEFAULT_PCT_3M,
        AVG(CASE WHEN IN_6M THEN NON_DEFAULT_FLAG END)  AS NON_DEFAULT_PCT_6M,
        AVG(CASE WHEN IN_12M THEN NON_DEFAULT_FLAG END) AS NON_DEFAULT_PCT_12M,
        AVG(NON_DEFAULT_FLAG)                           AS NON_DEFAULT_PCT_LIFETIME,

        -- ===== Average term between issuance and due date =====
        AVG(CASE WHEN IN_3M THEN ISSUE_TO_DUE_TERM END) AS ISSUE_TO_DUE_TERM_AVG_3M,
        MIN(CASE WHEN IN_3M THEN ISSUE_TO_DUE_TERM END) AS ISSUE_TO_DUE_TERM_MIN_3M,
        MAX(CASE WHEN IN_3M THEN ISSUE_TO_DUE_TERM END) AS ISSUE_TO_DUE_TERM_MAX_3M,

        AVG(CASE WHEN IN_6M THEN ISSUE_TO_DUE_TERM END) AS ISSUE_TO_DUE_TERM_AVG_6M,
        MIN(CASE WHEN IN_6M THEN ISSUE_TO_DUE_TERM END) AS ISSUE_TO_DUE_TERM_MIN_6M,
        MAX(CASE WHEN IN_6M THEN ISSUE_TO_DUE_TERM END) AS ISSUE_TO_DUE_TERM_MAX_6M,

        AVG(CASE WHEN IN_12M THEN ISSUE_TO_DUE_TERM END) AS ISSUE_TO_DUE_TERM_AVG_12M,
        MIN(CASE WHEN IN_12M THEN ISSUE_TO_DUE_TERM END) AS ISSUE_TO_DUE_TERM_MIN_12M,
        MAX(CASE WHEN IN_12M THEN ISSUE_TO_DUE_TERM END) AS ISSUE_TO_DUE_TERM_MAX_12M,

        AVG(ISSUE_TO_DUE_TERM) AS ISSUE_TO_DUE_TERM_AVG_LIFETIME,
        MIN(ISSUE_TO_DUE_TERM) AS ISSUE_TO_DUE_TERM_MIN_LIFETIME,
        MAX(ISSUE_TO_DUE_TERM) AS ISSUE_TO_DUE_TERM_MAX_LIFETIME,

        -- ===== Average days between issuance and payment =====
        AVG(CASE WHEN IN_3M THEN ISSUE_TO_PAYMENT_DAYS END)  AS ISSUE_TO_PAYMENT_AVG_3M,
        AVG(CASE WHEN IN_6M THEN ISSUE_TO_PAYMENT_DAYS END)  AS ISSUE_TO_PAYMENT_AVG_6M,
        AVG(CASE WHEN IN_12M THEN ISSUE_TO_PAYMENT_DAYS END) AS ISSUE_TO_PAYMENT_AVG_12M,
        AVG(ISSUE_TO_PAYMENT_DAYS)                           AS ISSUE_TO_PAYMENT_AVG_LIFETIME,

        -- ===== Charge amount per day =====
        AVG(CASE WHEN IN_3M THEN DAILY_CHARGE_AMOUNT END)  AS DAILY_CHARGE_AMOUNT_AVG_3M,
        AVG(CASE WHEN IN_6M THEN DAILY_CHARGE_AMOUNT END)  AS DAILY_CHARGE_AMOUNT_AVG_6M,
        AVG(CASE WHEN IN_12M THEN DAILY_CHARGE_AMOUNT END) AS DAILY_CHARGE_AMOUNT_AVG_12M,
        AVG(DAILY_CHARGE_AMOUNT)                           AS DAILY_CHARGE_AMOUNT_AVG_LIFETIME

    FROM payment_history_windows
    GROUP BY CLIENT_ID

)

SELECT

    h.DOCUMENT_ID                        
    , h.CLIENT_ID                        

    , CAST('{dt_ref}' AS DATE)              AS REF_DATE

    -- Delay metrics
    , f.DELAY_COUNT_SUM_3M
    , f.DELAY_COUNT_AVG_3M
    , f.DELAY_COUNT_MIN_3M
    , f.DELAY_COUNT_MAX_3M

    , f.DELAY_COUNT_SUM_6M
    , f.DELAY_COUNT_AVG_6M
    , f.DELAY_COUNT_MIN_6M
    , f.DELAY_COUNT_MAX_6M

    , f.DELAY_COUNT_SUM_12M
    , f.DELAY_COUNT_AVG_12M
    , f.DELAY_COUNT_MIN_12M
    , f.DELAY_COUNT_MAX_12M

    , f.DELAY_COUNT_SUM_LIFETIME
    , f.DELAY_COUNT_AVG_LIFETIME
    , f.DELAY_COUNT_MIN_LIFETIME
    , f.DELAY_COUNT_MAX_LIFETIME

    , f.DELAY_DAYS_SUM_3M
    , f.DELAY_DAYS_AVG_3M
    , f.DELAY_DAYS_MIN_3M
    , f.DELAY_DAYS_MAX_3M

    , f.DELAY_DAYS_SUM_6M
    , f.DELAY_DAYS_AVG_6M
    , f.DELAY_DAYS_MIN_6M
    , f.DELAY_DAYS_MAX_6M

    , f.DELAY_DAYS_SUM_12M
    , f.DELAY_DAYS_AVG_12M
    , f.DELAY_DAYS_MIN_12M
    , f.DELAY_DAYS_MAX_12M

    , f.DELAY_DAYS_SUM_LIFETIME
    , f.DELAY_DAYS_AVG_LIFETIME
    , f.DELAY_DAYS_MIN_LIFETIME
    , f.DELAY_DAYS_MAX_LIFETIME

    -- Payment amount metrics
    , f.AMOUNT_PAID_SUM_3M
    , f.AMOUNT_PAID_AVG_3M
    , f.AMOUNT_PAID_MIN_3M
    , f.AMOUNT_PAID_MAX_3M

    , f.AMOUNT_PAID_SUM_6M
    , f.AMOUNT_PAID_AVG_6M
    , f.AMOUNT_PAID_MIN_6M
    , f.AMOUNT_PAID_MAX_6M

    , f.AMOUNT_PAID_SUM_12M
    , f.AMOUNT_PAID_AVG_12M
    , f.AMOUNT_PAID_MIN_12M
    , f.AMOUNT_PAID_MAX_12M

    , f.AMOUNT_PAID_SUM_LIFETIME
    , f.AMOUNT_PAID_AVG_LIFETIME
    , f.AMOUNT_PAID_MIN_LIFETIME
    , f.AMOUNT_PAID_MAX_LIFETIME

    -- Event recency
    , f.DAYS_SINCE_LAST_DELAY
    , f.DAYS_SINCE_LAST_DEFAULT
    , f.DAYS_SINCE_LAST_PAYMENT

    -- Early payment
    , f.EARLY_COUNT_3M
    , f.EARLY_COUNT_6M
    , f.EARLY_COUNT_12M
    , f.EARLY_COUNT_LIFETIME

    , f.EARLY_DAYS_SUM_3M
    , f.EARLY_DAYS_AVG_3M

    , f.EARLY_DAYS_SUM_6M
    , f.EARLY_DAYS_AVG_6M

    , f.EARLY_DAYS_SUM_12M
    , f.EARLY_DAYS_AVG_12M

    , f.EARLY_DAYS_SUM_LIFETIME
    , f.EARLY_DAYS_AVG_LIFETIME

    -- On-time payments
    , f.ON_DUE_DATE_COUNT_3M
    , f.ON_DUE_DATE_COUNT_6M
    , f.ON_DUE_DATE_COUNT_12M
    , f.ON_DUE_DATE_COUNT_LIFETIME

    -- Invoices issued
    , f.INVOICES_ISSUED_3M
    , f.INVOICES_ISSUED_6M
    , f.INVOICES_ISSUED_12M
    , f.INVOICES_ISSUED_LIFETIME

    -- Behavior percentages
    , f.ON_TIME_PCT_3M
    , f.ON_TIME_PCT_6M
    , f.ON_TIME_PCT_12M
    , f.ON_TIME_PCT_LIFETIME

    , f.NON_DEFAULT_PCT_3M
    , f.NON_DEFAULT_PCT_6M
    , f.NON_DEFAULT_PCT_12M
    , f.NON_DEFAULT_PCT_LIFETIME

    -- Term between issue and due
    , f.ISSUE_TO_DUE_TERM_AVG_3M
    , f.ISSUE_TO_DUE_TERM_MIN_3M
    , f.ISSUE_TO_DUE_TERM_MAX_3M

    , f.ISSUE_TO_DUE_TERM_AVG_6M
    , f.ISSUE_TO_DUE_TERM_MIN_6M
    , f.ISSUE_TO_DUE_TERM_MAX_6M

    , f.ISSUE_TO_DUE_TERM_AVG_12M
    , f.ISSUE_TO_DUE_TERM_MIN_12M
    , f.ISSUE_TO_DUE_TERM_MAX_12M

    , f.ISSUE_TO_DUE_TERM_AVG_LIFETIME
    , f.ISSUE_TO_DUE_TERM_MIN_LIFETIME
    , f.ISSUE_TO_DUE_TERM_MAX_LIFETIME

    -- Days between issue and payment
    , f.ISSUE_TO_PAYMENT_AVG_3M
    , f.ISSUE_TO_PAYMENT_AVG_6M
    , f.ISSUE_TO_PAYMENT_AVG_12M
    , f.ISSUE_TO_PAYMENT_AVG_LIFETIME

    -- Charge amount per day
    , f.DAILY_CHARGE_AMOUNT_AVG_3M
    , f.DAILY_CHARGE_AMOUNT_AVG_6M
    , f.DAILY_CHARGE_AMOUNT_AVG_12M
    , f.DAILY_CHARGE_AMOUNT_AVG_LIFETIME

FROM payment_history h

LEFT JOIN payment_history_features f
    ON h.CLIENT_ID = f.CLIENT_ID