WITH tb_historico AS (

    SELECT
        ID_CLIENTE,
        ID_DOCUMENTO,
        SAFRA_REF,
        DATA_EMISSAO_DOCUMENTO,
        DATA_VENCIMENTO,
        DATA_PAGAMENTO,
        -- Dias de atraso (positivo = atraso, negativo = antecipado)
        DATEDIFF(DATA_PAGAMENTO, DATA_VENCIMENTO) AS DIAS_ATRASO,
        VALOR_A_PAGAR,
        -- Flags de status do pagamento
        CASE WHEN DATEDIFF(DATA_PAGAMENTO, DATA_VENCIMENTO) > 0 THEN 1 ELSE 0 END AS FLAG_ATRASO,
        CASE WHEN DATEDIFF(DATA_PAGAMENTO, DATA_VENCIMENTO) >= 5 THEN 1 ELSE 0 END AS FLAG_INADIMPLENCIA,
        CASE WHEN DATEDIFF(DATA_PAGAMENTO, DATA_VENCIMENTO) < 0 THEN 1 ELSE 0 END AS FLAG_ANTECIPADO,
        CASE WHEN DATEDIFF(DATA_PAGAMENTO, DATA_VENCIMENTO) = 0 THEN 1 ELSE 0 END AS FLAG_NO_VENCIMENTO,
        CASE WHEN DATEDIFF(DATA_PAGAMENTO, DATA_VENCIMENTO) <= 0 THEN 1 ELSE 0 END AS FLAG_EM_DIA,
        CASE WHEN DATEDIFF(DATA_PAGAMENTO, DATA_VENCIMENTO) <= 4 THEN 1 ELSE 0 END AS FLAG_FORA_INADIMPLENCIA,
        CASE WHEN DATEDIFF(DATA_PAGAMENTO, DATA_VENCIMENTO) < 0
             THEN ABS(DATEDIFF(DATA_PAGAMENTO, DATA_VENCIMENTO)) END AS DIAS_ANTECIPADO,
        -- Prazo entre emissão e vencimento/pagamento
        DATEDIFF(DATA_VENCIMENTO, DATA_EMISSAO_DOCUMENTO) AS PRAZO_EMISSAO_VENCIMENTO,
        DATEDIFF(DATA_PAGAMENTO, DATA_EMISSAO_DOCUMENTO) AS DIAS_EMISSAO_PAGAMENTO,
        CASE WHEN DATEDIFF(DATA_VENCIMENTO, DATA_EMISSAO_DOCUMENTO) > 0
             THEN VALOR_A_PAGAR / DATEDIFF(DATA_VENCIMENTO, DATA_EMISSAO_DOCUMENTO) END AS VALOR_COBRANCA_DIA
    FROM credit_score.data.pagamentos
        WHERE SAFRA_REF < '{dt_ref}'

),

tb_historico_janelas AS (

    SELECT
        *,
        -- Flags de janelas temporais
        SAFRA_REF > date_add(MONTH, -3, '{dt_ref}')  AS IN_3M,
        SAFRA_REF > date_add(MONTH, -6, '{dt_ref}')  AS IN_6M,
        SAFRA_REF > date_add(YEAR, -1, '{dt_ref}')   AS IN_12M
    FROM tb_historico

),

-- Snapshot do próximo boleto em aberto na data de referência
tb_proximo_vencimento AS (

    SELECT
        ID_CLIENTE,
        MIN(DATA_VENCIMENTO) AS PROXIMA_DATA_VENCIMENTO
    FROM credit_score.data.pagamentos
        WHERE DATA_PAGAMENTO IS NULL
          AND DATA_VENCIMENTO >= '{dt_ref}'
    GROUP BY ID_CLIENTE

),

fs_historico_pagamentos AS (

    SELECT

        ID_CLIENTE,

        -- ===== Quantidade de Atraso (contagem de pagamentos em atraso) =====
        COALESCE(SUM(CASE WHEN IN_3M THEN FLAG_ATRASO END), 0)  AS QT_ATRASO_SOMA_3M,
        AVG(CASE WHEN IN_3M THEN FLAG_ATRASO END)                AS QT_ATRASO_MEDIA_3M,
        MIN(CASE WHEN IN_3M THEN FLAG_ATRASO END)                AS QT_ATRASO_MIN_3M,
        MAX(CASE WHEN IN_3M THEN FLAG_ATRASO END)                AS QT_ATRASO_MAX_3M,

        COALESCE(SUM(CASE WHEN IN_6M THEN FLAG_ATRASO END), 0)  AS QT_ATRASO_SOMA_6M,
        AVG(CASE WHEN IN_6M THEN FLAG_ATRASO END)                AS QT_ATRASO_MEDIA_6M,
        MIN(CASE WHEN IN_6M THEN FLAG_ATRASO END)                AS QT_ATRASO_MIN_6M,
        MAX(CASE WHEN IN_6M THEN FLAG_ATRASO END)                AS QT_ATRASO_MAX_6M,

        COALESCE(SUM(CASE WHEN IN_12M THEN FLAG_ATRASO END), 0) AS QT_ATRASO_SOMA_12M,
        AVG(CASE WHEN IN_12M THEN FLAG_ATRASO END)               AS QT_ATRASO_MEDIA_12M,
        MIN(CASE WHEN IN_12M THEN FLAG_ATRASO END)               AS QT_ATRASO_MIN_12M,
        MAX(CASE WHEN IN_12M THEN FLAG_ATRASO END)               AS QT_ATRASO_MAX_12M,

        COALESCE(SUM(FLAG_ATRASO), 0)                            AS QT_ATRASO_SOMA_VIDA,
        AVG(FLAG_ATRASO)                                         AS QT_ATRASO_MEDIA_VIDA,
        MIN(FLAG_ATRASO)                                         AS QT_ATRASO_MIN_VIDA,
        MAX(FLAG_ATRASO)                                         AS QT_ATRASO_MAX_VIDA,

        -- ===== Atraso em Dias =====
        COALESCE(SUM(CASE WHEN IN_3M THEN DIAS_ATRASO END), 0)  AS DIAS_ATRASO_SOMA_3M,
        AVG(CASE WHEN IN_3M THEN DIAS_ATRASO END)  AS DIAS_ATRASO_MEDIA_3M,
        MIN(CASE WHEN IN_3M THEN DIAS_ATRASO END)  AS DIAS_ATRASO_MIN_3M,
        MAX(CASE WHEN IN_3M THEN DIAS_ATRASO END)  AS DIAS_ATRASO_MAX_3M,

        COALESCE(SUM(CASE WHEN IN_6M THEN DIAS_ATRASO END), 0)  AS DIAS_ATRASO_SOMA_6M,
        AVG(CASE WHEN IN_6M THEN DIAS_ATRASO END)  AS DIAS_ATRASO_MEDIA_6M,
        MIN(CASE WHEN IN_6M THEN DIAS_ATRASO END)  AS DIAS_ATRASO_MIN_6M,
        MAX(CASE WHEN IN_6M THEN DIAS_ATRASO END)  AS DIAS_ATRASO_MAX_6M,

        COALESCE(SUM(CASE WHEN IN_12M THEN DIAS_ATRASO END), 0) AS DIAS_ATRASO_SOMA_12M,
        AVG(CASE WHEN IN_12M THEN DIAS_ATRASO END) AS DIAS_ATRASO_MEDIA_12M,
        MIN(CASE WHEN IN_12M THEN DIAS_ATRASO END) AS DIAS_ATRASO_MIN_12M,
        MAX(CASE WHEN IN_12M THEN DIAS_ATRASO END) AS DIAS_ATRASO_MAX_12M,

        COALESCE(SUM(DIAS_ATRASO), 0) AS DIAS_ATRASO_SOMA_VIDA,
        AVG(DIAS_ATRASO) AS DIAS_ATRASO_MEDIA_VIDA,
        MIN(DIAS_ATRASO) AS DIAS_ATRASO_MIN_VIDA,
        MAX(DIAS_ATRASO) AS DIAS_ATRASO_MAX_VIDA,

        -- ===== Valor Total Pago =====
        COALESCE(SUM(CASE WHEN IN_3M THEN VALOR_A_PAGAR END), 0) AS VALOR_A_PAGAR_SOMA_3M,
        AVG(CASE WHEN IN_3M THEN VALOR_A_PAGAR END)               AS VALOR_A_PAGAR_MEDIA_3M,
        MIN(CASE WHEN IN_3M THEN VALOR_A_PAGAR END)               AS VALOR_A_PAGAR_MIN_3M,
        MAX(CASE WHEN IN_3M THEN VALOR_A_PAGAR END)               AS VALOR_A_PAGAR_MAX_3M,

        COALESCE(SUM(CASE WHEN IN_6M THEN VALOR_A_PAGAR END), 0) AS VALOR_A_PAGAR_SOMA_6M,
        AVG(CASE WHEN IN_6M THEN VALOR_A_PAGAR END)               AS VALOR_A_PAGAR_MEDIA_6M,
        MIN(CASE WHEN IN_6M THEN VALOR_A_PAGAR END)               AS VALOR_A_PAGAR_MIN_6M,
        MAX(CASE WHEN IN_6M THEN VALOR_A_PAGAR END)               AS VALOR_A_PAGAR_MAX_6M,

        COALESCE(SUM(CASE WHEN IN_12M THEN VALOR_A_PAGAR END), 0) AS VALOR_A_PAGAR_SOMA_12M,
        AVG(CASE WHEN IN_12M THEN VALOR_A_PAGAR END)               AS VALOR_A_PAGAR_MEDIA_12M,
        MIN(CASE WHEN IN_12M THEN VALOR_A_PAGAR END)               AS VALOR_A_PAGAR_MIN_12M,
        MAX(CASE WHEN IN_12M THEN VALOR_A_PAGAR END)               AS VALOR_A_PAGAR_MAX_12M,

        COALESCE(SUM(VALOR_A_PAGAR), 0) AS VALOR_A_PAGAR_SOMA_VIDA,
        AVG(VALOR_A_PAGAR)              AS VALOR_A_PAGAR_MEDIA_VIDA,
        MIN(VALOR_A_PAGAR)              AS VALOR_A_PAGAR_MIN_VIDA,
        MAX(VALOR_A_PAGAR)              AS VALOR_A_PAGAR_MAX_VIDA,

        -- ===== Recência: dias desde último evento relevante =====
        DATEDIFF('{dt_ref}', MAX(CASE WHEN FLAG_ATRASO = 1 THEN DATA_VENCIMENTO END))        AS DIAS_DESDE_ULTIMO_ATRASO,
        DATEDIFF('{dt_ref}', MAX(CASE WHEN FLAG_INADIMPLENCIA = 1 THEN DATA_VENCIMENTO END)) AS DIAS_DESDE_ULTIMA_INADIMPLENCIA,
        DATEDIFF('{dt_ref}', MAX(DATA_PAGAMENTO))                                            AS DIAS_DESDE_ULTIMO_PAGAMENTO,

        -- ===== Quantidade de Pagamentos Antecipados =====
        COALESCE(SUM(CASE WHEN IN_3M THEN FLAG_ANTECIPADO END), 0)  AS QT_ANTECIPADO_3M,
        COALESCE(SUM(CASE WHEN IN_6M THEN FLAG_ANTECIPADO END), 0)  AS QT_ANTECIPADO_6M,
        COALESCE(SUM(CASE WHEN IN_12M THEN FLAG_ANTECIPADO END), 0) AS QT_ANTECIPADO_12M,
        COALESCE(SUM(FLAG_ANTECIPADO), 0)                            AS QT_ANTECIPADO_VIDA,

        -- ===== Média e Soma de Dias Antecipados =====
        COALESCE(SUM(CASE WHEN IN_3M THEN DIAS_ANTECIPADO END), 0)  AS DIAS_ANTECIPADO_SOMA_3M,
        AVG(CASE WHEN IN_3M THEN DIAS_ANTECIPADO END)  AS DIAS_ANTECIPADO_MEDIA_3M,

        COALESCE(SUM(CASE WHEN IN_6M THEN DIAS_ANTECIPADO END), 0)  AS DIAS_ANTECIPADO_SOMA_6M,
        AVG(CASE WHEN IN_6M THEN DIAS_ANTECIPADO END)  AS DIAS_ANTECIPADO_MEDIA_6M,

        COALESCE(SUM(CASE WHEN IN_12M THEN DIAS_ANTECIPADO END), 0) AS DIAS_ANTECIPADO_SOMA_12M,
        AVG(CASE WHEN IN_12M THEN DIAS_ANTECIPADO END) AS DIAS_ANTECIPADO_MEDIA_12M,

        COALESCE(SUM(DIAS_ANTECIPADO), 0) AS DIAS_ANTECIPADO_SOMA_VIDA,
        AVG(DIAS_ANTECIPADO) AS DIAS_ANTECIPADO_MEDIA_VIDA,

        -- ===== Quantidade de Pagamentos no Vencimento =====
        COALESCE(SUM(CASE WHEN IN_3M THEN FLAG_NO_VENCIMENTO END), 0)  AS QT_NO_VENCIMENTO_3M,
        COALESCE(SUM(CASE WHEN IN_6M THEN FLAG_NO_VENCIMENTO END), 0)  AS QT_NO_VENCIMENTO_6M,
        COALESCE(SUM(CASE WHEN IN_12M THEN FLAG_NO_VENCIMENTO END), 0) AS QT_NO_VENCIMENTO_12M,
        COALESCE(SUM(FLAG_NO_VENCIMENTO), 0)                            AS QT_NO_VENCIMENTO_VIDA,

        -- ===== Quantidade de Boletos Emitidos =====
        COALESCE(COUNT(CASE WHEN IN_3M THEN 1 END), 0)  AS QT_BOLETOS_EMITIDOS_3M,
        COALESCE(COUNT(CASE WHEN IN_6M THEN 1 END), 0)  AS QT_BOLETOS_EMITIDOS_6M,
        COALESCE(COUNT(CASE WHEN IN_12M THEN 1 END), 0) AS QT_BOLETOS_EMITIDOS_12M,
        COALESCE(COUNT(*), 0)                            AS QT_BOLETOS_EMITIDOS_VIDA,

        -- ===== Valor Solicitado =====
        AVG(CASE WHEN IN_3M THEN VALOR_A_PAGAR END)  AS VALOR_SOLICITADO_MEDIA_3M,
        MAX(CASE WHEN IN_3M THEN VALOR_A_PAGAR END)  AS VALOR_SOLICITADO_MAX_3M,

        AVG(CASE WHEN IN_6M THEN VALOR_A_PAGAR END)  AS VALOR_SOLICITADO_MEDIA_6M,
        MAX(CASE WHEN IN_6M THEN VALOR_A_PAGAR END)  AS VALOR_SOLICITADO_MAX_6M,

        AVG(CASE WHEN IN_12M THEN VALOR_A_PAGAR END) AS VALOR_SOLICITADO_MEDIA_12M,
        MAX(CASE WHEN IN_12M THEN VALOR_A_PAGAR END) AS VALOR_SOLICITADO_MAX_12M,

        AVG(VALOR_A_PAGAR) AS VALOR_SOLICITADO_MEDIA_VIDA,
        MAX(VALOR_A_PAGAR) AS VALOR_SOLICITADO_MAX_VIDA,

        -- ===== Percentual de Pagamentos em Dia (não atrasados) =====
        AVG(CASE WHEN IN_3M THEN FLAG_EM_DIA END)  AS PCT_EM_DIA_3M,
        AVG(CASE WHEN IN_6M THEN FLAG_EM_DIA END)  AS PCT_EM_DIA_6M,
        AVG(CASE WHEN IN_12M THEN FLAG_EM_DIA END) AS PCT_EM_DIA_12M,
        AVG(FLAG_EM_DIA)                            AS PCT_EM_DIA_VIDA,

        -- ===== Percentual de Pagamentos Fora da Inadimplência (atraso <= 4 dias) =====
        AVG(CASE WHEN IN_3M THEN FLAG_FORA_INADIMPLENCIA END)  AS PCT_FORA_INADIMPLENCIA_3M,
        AVG(CASE WHEN IN_6M THEN FLAG_FORA_INADIMPLENCIA END)  AS PCT_FORA_INADIMPLENCIA_6M,
        AVG(CASE WHEN IN_12M THEN FLAG_FORA_INADIMPLENCIA END) AS PCT_FORA_INADIMPLENCIA_12M,
        AVG(FLAG_FORA_INADIMPLENCIA)                            AS PCT_FORA_INADIMPLENCIA_VIDA,

        -- ===== Prazo Médio entre Emissão e Vencimento =====
        AVG(CASE WHEN IN_3M THEN PRAZO_EMISSAO_VENCIMENTO END) AS PRAZO_EMISSAO_VENCIMENTO_MEDIA_3M,
        MIN(CASE WHEN IN_3M THEN PRAZO_EMISSAO_VENCIMENTO END) AS PRAZO_EMISSAO_VENCIMENTO_MIN_3M,
        MAX(CASE WHEN IN_3M THEN PRAZO_EMISSAO_VENCIMENTO END) AS PRAZO_EMISSAO_VENCIMENTO_MAX_3M,

        AVG(CASE WHEN IN_6M THEN PRAZO_EMISSAO_VENCIMENTO END) AS PRAZO_EMISSAO_VENCIMENTO_MEDIA_6M,
        MIN(CASE WHEN IN_6M THEN PRAZO_EMISSAO_VENCIMENTO END) AS PRAZO_EMISSAO_VENCIMENTO_MIN_6M,
        MAX(CASE WHEN IN_6M THEN PRAZO_EMISSAO_VENCIMENTO END) AS PRAZO_EMISSAO_VENCIMENTO_MAX_6M,

        AVG(CASE WHEN IN_12M THEN PRAZO_EMISSAO_VENCIMENTO END) AS PRAZO_EMISSAO_VENCIMENTO_MEDIA_12M,
        MIN(CASE WHEN IN_12M THEN PRAZO_EMISSAO_VENCIMENTO END) AS PRAZO_EMISSAO_VENCIMENTO_MIN_12M,
        MAX(CASE WHEN IN_12M THEN PRAZO_EMISSAO_VENCIMENTO END) AS PRAZO_EMISSAO_VENCIMENTO_MAX_12M,

        AVG(PRAZO_EMISSAO_VENCIMENTO) AS PRAZO_EMISSAO_VENCIMENTO_MEDIA_VIDA,
        MIN(PRAZO_EMISSAO_VENCIMENTO) AS PRAZO_EMISSAO_VENCIMENTO_MIN_VIDA,
        MAX(PRAZO_EMISSAO_VENCIMENTO) AS PRAZO_EMISSAO_VENCIMENTO_MAX_VIDA,

        -- ===== Média de Dias entre Emissão e Pagamento =====
        AVG(CASE WHEN IN_3M THEN DIAS_EMISSAO_PAGAMENTO END)  AS DIAS_EMISSAO_PAGAMENTO_MEDIA_3M,
        AVG(CASE WHEN IN_6M THEN DIAS_EMISSAO_PAGAMENTO END)  AS DIAS_EMISSAO_PAGAMENTO_MEDIA_6M,
        AVG(CASE WHEN IN_12M THEN DIAS_EMISSAO_PAGAMENTO END) AS DIAS_EMISSAO_PAGAMENTO_MEDIA_12M,
        AVG(DIAS_EMISSAO_PAGAMENTO)                            AS DIAS_EMISSAO_PAGAMENTO_MEDIA_VIDA,

        -- ===== Valor da Cobrança por Dia =====
        AVG(CASE WHEN IN_3M THEN VALOR_COBRANCA_DIA END)  AS VALOR_COBRANCA_DIA_MEDIA_3M,
        AVG(CASE WHEN IN_6M THEN VALOR_COBRANCA_DIA END)  AS VALOR_COBRANCA_DIA_MEDIA_6M,
        AVG(CASE WHEN IN_12M THEN VALOR_COBRANCA_DIA END) AS VALOR_COBRANCA_DIA_MEDIA_12M,
        AVG(VALOR_COBRANCA_DIA)                            AS VALOR_COBRANCA_DIA_MEDIA_VIDA

    FROM tb_historico_janelas
    GROUP BY ID_CLIENTE

)

SELECT

    h.ID_DOCUMENTO,
    h.ID_CLIENTE,

    CAST('{dt_ref}' AS DATE) AS DATA_REF,

    -- Métricas de atraso
    f.QT_ATRASO_SOMA_3M,
    f.QT_ATRASO_MEDIA_3M,
    f.QT_ATRASO_MIN_3M,
    f.QT_ATRASO_MAX_3M,

    f.QT_ATRASO_SOMA_6M,
    f.QT_ATRASO_MEDIA_6M,
    f.QT_ATRASO_MIN_6M,
    f.QT_ATRASO_MAX_6M,

    f.QT_ATRASO_SOMA_12M,
    f.QT_ATRASO_MEDIA_12M,
    f.QT_ATRASO_MIN_12M,
    f.QT_ATRASO_MAX_12M,

    f.QT_ATRASO_SOMA_VIDA,
    f.QT_ATRASO_MEDIA_VIDA,
    f.QT_ATRASO_MIN_VIDA,
    f.QT_ATRASO_MAX_VIDA,

    f.DIAS_ATRASO_SOMA_3M,
    f.DIAS_ATRASO_MEDIA_3M,
    f.DIAS_ATRASO_MIN_3M,
    f.DIAS_ATRASO_MAX_3M,

    f.DIAS_ATRASO_SOMA_6M,
    f.DIAS_ATRASO_MEDIA_6M,
    f.DIAS_ATRASO_MIN_6M,
    f.DIAS_ATRASO_MAX_6M,

    f.DIAS_ATRASO_SOMA_12M,
    f.DIAS_ATRASO_MEDIA_12M,
    f.DIAS_ATRASO_MIN_12M,
    f.DIAS_ATRASO_MAX_12M,

    f.DIAS_ATRASO_SOMA_VIDA,
    f.DIAS_ATRASO_MEDIA_VIDA,
    f.DIAS_ATRASO_MIN_VIDA,
    f.DIAS_ATRASO_MAX_VIDA,

    -- Métricas de valor pago
    f.VALOR_A_PAGAR_SOMA_3M,
    f.VALOR_A_PAGAR_MEDIA_3M,
    f.VALOR_A_PAGAR_MIN_3M,
    f.VALOR_A_PAGAR_MAX_3M,

    f.VALOR_A_PAGAR_SOMA_6M,
    f.VALOR_A_PAGAR_MEDIA_6M,
    f.VALOR_A_PAGAR_MIN_6M,
    f.VALOR_A_PAGAR_MAX_6M,

    f.VALOR_A_PAGAR_SOMA_12M,
    f.VALOR_A_PAGAR_MEDIA_12M,
    f.VALOR_A_PAGAR_MIN_12M,
    f.VALOR_A_PAGAR_MAX_12M,

    f.VALOR_A_PAGAR_SOMA_VIDA,
    f.VALOR_A_PAGAR_MEDIA_VIDA,
    f.VALOR_A_PAGAR_MIN_VIDA,
    f.VALOR_A_PAGAR_MAX_VIDA,

    -- Recência dos eventos
    f.DIAS_DESDE_ULTIMO_ATRASO,
    f.DIAS_DESDE_ULTIMA_INADIMPLENCIA,
    f.DIAS_DESDE_ULTIMO_PAGAMENTO,

    -- Antecipação
    f.QT_ANTECIPADO_3M,
    f.QT_ANTECIPADO_6M,
    f.QT_ANTECIPADO_12M,
    f.QT_ANTECIPADO_VIDA,

    f.DIAS_ANTECIPADO_SOMA_3M,
    f.DIAS_ANTECIPADO_MEDIA_3M,

    f.DIAS_ANTECIPADO_SOMA_6M,
    f.DIAS_ANTECIPADO_MEDIA_6M,

    f.DIAS_ANTECIPADO_SOMA_12M,
    f.DIAS_ANTECIPADO_MEDIA_12M,

    f.DIAS_ANTECIPADO_SOMA_VIDA,
    f.DIAS_ANTECIPADO_MEDIA_VIDA,

    -- Pagamentos no vencimento
    f.QT_NO_VENCIMENTO_3M,
    f.QT_NO_VENCIMENTO_6M,
    f.QT_NO_VENCIMENTO_12M,
    f.QT_NO_VENCIMENTO_VIDA,

    -- Boletos emitidos
    f.QT_BOLETOS_EMITIDOS_3M,
    f.QT_BOLETOS_EMITIDOS_6M,
    f.QT_BOLETOS_EMITIDOS_12M,
    f.QT_BOLETOS_EMITIDOS_VIDA,

    -- Percentuais de comportamento
    f.PCT_EM_DIA_3M,
    f.PCT_EM_DIA_6M,
    f.PCT_EM_DIA_12M,
    f.PCT_EM_DIA_VIDA,

    f.PCT_FORA_INADIMPLENCIA_3M,
    f.PCT_FORA_INADIMPLENCIA_6M,
    f.PCT_FORA_INADIMPLENCIA_12M,
    f.PCT_FORA_INADIMPLENCIA_VIDA,

    -- Prazo entre emissão e vencimento
    f.PRAZO_EMISSAO_VENCIMENTO_MEDIA_3M,
    f.PRAZO_EMISSAO_VENCIMENTO_MIN_3M,
    f.PRAZO_EMISSAO_VENCIMENTO_MAX_3M,

    f.PRAZO_EMISSAO_VENCIMENTO_MEDIA_6M,
    f.PRAZO_EMISSAO_VENCIMENTO_MIN_6M,
    f.PRAZO_EMISSAO_VENCIMENTO_MAX_6M,

    f.PRAZO_EMISSAO_VENCIMENTO_MEDIA_12M,
    f.PRAZO_EMISSAO_VENCIMENTO_MIN_12M,
    f.PRAZO_EMISSAO_VENCIMENTO_MAX_12M,

    f.PRAZO_EMISSAO_VENCIMENTO_MEDIA_VIDA,
    f.PRAZO_EMISSAO_VENCIMENTO_MIN_VIDA,
    f.PRAZO_EMISSAO_VENCIMENTO_MAX_VIDA,

    -- Dias entre emissão e pagamento
    f.DIAS_EMISSAO_PAGAMENTO_MEDIA_3M,
    f.DIAS_EMISSAO_PAGAMENTO_MEDIA_6M,
    f.DIAS_EMISSAO_PAGAMENTO_MEDIA_12M,
    f.DIAS_EMISSAO_PAGAMENTO_MEDIA_VIDA,

    -- Valor da cobrança por dia
    f.VALOR_COBRANCA_DIA_MEDIA_3M,
    f.VALOR_COBRANCA_DIA_MEDIA_6M,
    f.VALOR_COBRANCA_DIA_MEDIA_12M,
    f.VALOR_COBRANCA_DIA_MEDIA_VIDA

FROM tb_historico h

LEFT JOIN fs_historico_pagamentos f
    ON h.ID_CLIENTE = f.ID_CLIENTE